app:
    resource: '@AppBundle/Controller/'
    type: annotation

index:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: home_page
        permanent: true